// Generated by gencpp from file tf/FrameGraph.msg
// DO NOT EDIT!


#ifndef TF_MESSAGE_FRAMEGRAPH_H
#define TF_MESSAGE_FRAMEGRAPH_H

#include <ros/service_traits.h>


#include <tf/FrameGraphRequest.h>
#include <tf/FrameGraphResponse.h>


namespace tf
{

struct FrameGraph
{

typedef FrameGraphRequest Request;
typedef FrameGraphResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FrameGraph
} // namespace tf


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tf::FrameGraph > {
  static const char* value()
  {
    return "c4af9ac907e58e906eb0b6e3c58478c0";
  }

  static const char* value(const ::tf::FrameGraph&) { return value(); }
};

template<>
struct DataType< ::tf::FrameGraph > {
  static const char* value()
  {
    return "tf/FrameGraph";
  }

  static const char* value(const ::tf::FrameGraph&) { return value(); }
};


// service_traits::MD5Sum< ::tf::FrameGraphRequest> should match
// service_traits::MD5Sum< ::tf::FrameGraph >
template<>
struct MD5Sum< ::tf::FrameGraphRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tf::FrameGraph >::value();
  }
  static const char* value(const ::tf::FrameGraphRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tf::FrameGraphRequest> should match
// service_traits::DataType< ::tf::FrameGraph >
template<>
struct DataType< ::tf::FrameGraphRequest>
{
  static const char* value()
  {
    return DataType< ::tf::FrameGraph >::value();
  }
  static const char* value(const ::tf::FrameGraphRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tf::FrameGraphResponse> should match
// service_traits::MD5Sum< ::tf::FrameGraph >
template<>
struct MD5Sum< ::tf::FrameGraphResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tf::FrameGraph >::value();
  }
  static const char* value(const ::tf::FrameGraphResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tf::FrameGraphResponse> should match
// service_traits::DataType< ::tf::FrameGraph >
template<>
struct DataType< ::tf::FrameGraphResponse>
{
  static const char* value()
  {
    return DataType< ::tf::FrameGraph >::value();
  }
  static const char* value(const ::tf::FrameGraphResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TF_MESSAGE_FRAMEGRAPH_H
