// Generated by gencpp from file tf2_msgs/FrameGraph.msg
// DO NOT EDIT!


#ifndef TF2_MSGS_MESSAGE_FRAMEGRAPH_H
#define TF2_MSGS_MESSAGE_FRAMEGRAPH_H

#include <ros/service_traits.h>


#include <tf2_msgs/FrameGraphRequest.h>
#include <tf2_msgs/FrameGraphResponse.h>


namespace tf2_msgs
{

struct FrameGraph
{

typedef FrameGraphRequest Request;
typedef FrameGraphResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FrameGraph
} // namespace tf2_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tf2_msgs::FrameGraph > {
  static const char* value()
  {
    return "437ea58e9463815a0d511c7326b686b0";
  }

  static const char* value(const ::tf2_msgs::FrameGraph&) { return value(); }
};

template<>
struct DataType< ::tf2_msgs::FrameGraph > {
  static const char* value()
  {
    return "tf2_msgs/FrameGraph";
  }

  static const char* value(const ::tf2_msgs::FrameGraph&) { return value(); }
};


// service_traits::MD5Sum< ::tf2_msgs::FrameGraphRequest> should match
// service_traits::MD5Sum< ::tf2_msgs::FrameGraph >
template<>
struct MD5Sum< ::tf2_msgs::FrameGraphRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tf2_msgs::FrameGraph >::value();
  }
  static const char* value(const ::tf2_msgs::FrameGraphRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tf2_msgs::FrameGraphRequest> should match
// service_traits::DataType< ::tf2_msgs::FrameGraph >
template<>
struct DataType< ::tf2_msgs::FrameGraphRequest>
{
  static const char* value()
  {
    return DataType< ::tf2_msgs::FrameGraph >::value();
  }
  static const char* value(const ::tf2_msgs::FrameGraphRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tf2_msgs::FrameGraphResponse> should match
// service_traits::MD5Sum< ::tf2_msgs::FrameGraph >
template<>
struct MD5Sum< ::tf2_msgs::FrameGraphResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tf2_msgs::FrameGraph >::value();
  }
  static const char* value(const ::tf2_msgs::FrameGraphResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tf2_msgs::FrameGraphResponse> should match
// service_traits::DataType< ::tf2_msgs::FrameGraph >
template<>
struct DataType< ::tf2_msgs::FrameGraphResponse>
{
  static const char* value()
  {
    return DataType< ::tf2_msgs::FrameGraph >::value();
  }
  static const char* value(const ::tf2_msgs::FrameGraphResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TF2_MSGS_MESSAGE_FRAMEGRAPH_H
