; Auto-generated. Do not edit!


(cl:in-package tf2_msgs-msg)


;//! \htmlinclude LookupTransformFeedback.msg.html

(cl:defclass <LookupTransformFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass LookupTransformFeedback (<LookupTransformFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LookupTransformFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LookupTransformFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tf2_msgs-msg:<LookupTransformFeedback> is deprecated: use tf2_msgs-msg:LookupTransformFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LookupTransformFeedback>) ostream)
  "Serializes a message object of type '<LookupTransformFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LookupTransformFeedback>) istream)
  "Deserializes a message object of type '<LookupTransformFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LookupTransformFeedback>)))
  "Returns string type for a message object of type '<LookupTransformFeedback>"
  "tf2_msgs/LookupTransformFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LookupTransformFeedback)))
  "Returns string type for a message object of type 'LookupTransformFeedback"
  "tf2_msgs/LookupTransformFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LookupTransformFeedback>)))
  "Returns md5sum for a message object of type '<LookupTransformFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LookupTransformFeedback)))
  "Returns md5sum for a message object of type 'LookupTransformFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LookupTransformFeedback>)))
  "Returns full string definition for message of type '<LookupTransformFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LookupTransformFeedback)))
  "Returns full string definition for message of type 'LookupTransformFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LookupTransformFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LookupTransformFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'LookupTransformFeedback
))
